config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "application#home"
  
  get 'browse', to: 'raffles#browse'
  post 'browse', to: 'raffles#browse'
  patch 'funds', to: 'users/users#funds'
  
  
  resources :raffles, only: [:create, :new, :edit, :update, :show, :destroy] do 
    resources :entries, only: [:index, :new]
    post '/entries/new', to: 'entries#create'
    get 'entered_users', to: 'entries#users'
    post 'winner', to: 'entries#winner'  
  end

  


  resources :users, path: 'accounts', param: :username, controller: 'users/users', only: [:show] do
    resources :raffles, only: [:show, :index, :new]
  end
  
  
  devise_for :users, path: 'account', path_names: { sign_in: "login", sign_out: 'logout'},
              controllers: {sessions: 'users/sessions',
                 registrations: 'users/registrations',
                 omniauth_callbacks: 'users/omniauth_callbacks'
                }
  
end

app/models/raffle.rb
class Raffle < ApplicationRecord
  paginates_per 6

  belongs_to :user
  belongs_to :winner, class_name: 'User', foreign_key: 'winner_id', optional: true

  has_many :entries
  has_many :entered_users, through: :entries

  

  # Validations 
  validates :title, :item, :goal, :description, presence: true 
  validates :description, length: {maximum: 100}
  validates :item, length: {maximum: 15 }
  validates :title, length: {maximum: 10}

  scope :raffle_search, ->(title) {where("title LIKE ?", "%#{title}%") if title.present? } 
  scope :first_6, ->(user_id) {where("user_id = ?", user_id).order(:created_at).reverse_order.limit(6) }

end

app/controllers/raffles_controller.rb
class RafflesController < ApplicationController
  before_action :set_user_raffle, only: [:edit, :update]
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:browse, :show]
  
  def browse
    begin
      @raffles = Raffle.raffle_search(raffle_params.to_hash['title']).order(:created_at).reverse_order.page(params[:page]) 
      @message = "Your search - #{raffle_params.to_hash['title']} - did not match any raffle tiles."
    rescue ActionController::ParameterMissing
      @raffles = Raffle.order(:created_at).reverse_order.page(params[:page])
    end
  end 

  def index
    user = User.find_by(username: params[:user_username])
    if user.nil? 
      user = current_user
      flash[:alert] = "#{params[:user_username]} could not be found."
    end
    @raffles = user.raffles.order(:created_at).reverse_order.page(params[:page])
  end

  def show 
    @raffle = Raffle.find(params[:id])
  end 

  def new
    @raffle = Raffle.new
  end

  def create 
    @raffle = current_user.raffles.build(raffle_params)
    if @raffle.valid?
      @raffle.cost = @raffle.goal / 20
      @raffle.save
      redirect_to user_raffles_path(current_user), notice: 'Raffle created' 
    else
      render :new
    end
  end

  def edit
    if @raffle.nil? 
      redirect_to browse_path, alert: "Raffle unkown"
    end 
  end 

  def update
    if @raffle.update(raffle_params)
      redirect_to raffle_path(@raffle), notice: 'Raffle updated'
    else
      redirect_to edit_raffle_path, alert: "something is wrong"
    end
  end 

  def destroy 
    Raffle.find(params[:id]).destroy
    redirect_to user_raffles_path(current_user)
  end

  private

  def raffle_params 
    params.require(:raffle).permit(:title, :item, :goal, :description)
  end

   
  def set_user_raffle
    @raffle = current_user.raffles.find(params[:id])
  end
end 

app/helpers/raffles_helper.rb
module RafflesHelper
  def percentage(raffle)
    (raffle.amount.to_int * 100 ) / raffle.goal.to_int 
  end

  def is_complete?(raffle)
    percentage(raffle) == 100
  end
end

app/views/raffles/_form.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-lg-6">
      <h2><%= action %> Raffle</h2>
      
      <%= form_for raffle do |r| %>
        <% if raffle.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(raffle.errors.count, "error") %> prohibited this post from being saved:</h2>
      
            <ul>
            <% raffle.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        
        <div class="form-group">
          <%= r.label :title %>
          <%= r.text_field :title, class:"form-control" %>
        
        
        
          <%= r.label :item %>
          <%= r.text_field :item, class:"form-control" %>
        
      
        
          <%= r.label :goal %>
          <%= r.text_field :goal, class:"form-control" %>
        
      
        
          <%= r.label :description %>
          <%= r.text_area :description, class: "form-control" %>
        </div>
      
        <%= r.submit "#{action} Raffle", class: "btn btn-primary form-btn" %>
      <% end %>

    </div>
  </div>
</div>

app/views/raffles/_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-outline-success btn-sm" id="user-currency" data-toggle="modal" data-target="#exampleModal">
  <%= number_to_currency(current_user.funds) %> 
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Funds</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for current_user, url: funds_path, class: "center", method: :patch do |u|%>
          <%= u.label :funds %>
          <%= u.number_field :funds, value: number_to_currency(current_user.funds), step: :any %>
      </div>
      <div class="modal-footer">
          <%= u.submit "Add Funds", class: "btn btn-primary" %>
        <% end %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="window.location.reload();">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/raffles/_raffles.html.erb
<div class="raffle-set">
  <% raffles.each do |raffle| %>
    <%= link_to raffle_path(raffle) do %>
      <div class="container">
        <div class="raffle" style="<%= "background: rgb(0, 207, 254);" if is_complete?(raffle) %>" >
          <h2><%= raffle.title %></h2>
          <p><strong>Item:</strong><%= raffle.item%></p>
          <p><strong>Goal:</strong><%= number_to_currency(raffle.goal) %></p>
          <p><strong>Cost:</strong><%= number_to_currency(raffle.cost) %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/raffles/browse.html.erb
<% if !@raffles.empty? %> 
  <%= render partial: 'raffles/raffles', locals: {raffles: @raffles} %>
  <%= paginate @raffles %>
<% else %>
  <p style="text-align: center;"><%= @message %></p>
<% end %>

app/views/raffles/edit.html.erb
<%= render partial: "raffles/form", locals: {raffle: @raffle, action: "Edit" }%>
<%= link_to "Delete", @raffle, method: :delete, data: {confirm: "Are you sure you wish to delete?"} %>

app/views/raffles/entered.html.erb
<%= render partial: 'raffles/raffles', locals: {raffles: @raffles} %>

app/views/raffles/home.html.erb
username: <%= current_user.username %>
<br>
name: <%= current_user.name %>
<br>
email: <%= current_user.email %>

app/views/raffles/index.html.erb
<% if !@raffles.empty? %>
  <%= render partial: 'raffles/raffles', locals: {raffles: @raffles} %> 
  <%= paginate @raffles %>
<% else %>
  <h1 style="text-align: center;">You do not have any Raffles yet</h1> 
  <h1 style="text-align: center;">Create one <%= link_to "here.", new_raffle_path %></h1>
<% end %>

app/views/raffles/new.html.erb
<%= render partial: "raffles/form", locals: {raffle: @raffle, action: "New" } %>

app/views/raffles/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-lg-4">

      <h1><%= @raffle.title %></h1>
      <% if current_user != @raffle.user %>
        <p><strong>Owner: </strong><%= link_to @raffle.user.username, user_path(@raffle.user) %></p>
      <% end %>
      <p><strong>Item: </strong><%= @raffle.item %></p>
      <p><strong>Goal: </strong><%= number_to_currency(@raffle.goal) %></p>
      <div class="progress">
        <div class="progress-bar bg-success" role="progressbar"  style="width: <%= percentage @raffle %>%" aria-valuenow="<%= @raffle.amount.to_int %>" aria-valuemin="0" aria-valuemax="<%= @raffle.goal.to_int %>"></div>
      </div>
      <p><strong>Cost: </strong><%= number_to_currency(@raffle.cost) %></p>
      <p><strong>Description: </strong><%= @raffle.description %></p>
      

      <% if current_user == @raffle.user %>
        <%= link_to "View Entered users", raffle_entered_users_path(@raffle), class: "btn btn-primary"  %>
      <% end %> 

      <br>
      <% if @raffle.winner.nil? %>
        <% if !user_signed_in? %>
          <%= link_to "login", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %> 
        <% elsif current_user != @raffle.user && !@raffle.entered_users.include?(current_user) %>
          <%= link_to "Enter", new_raffle_entry_path(@raffle), class:"btn btn-success" %>
        <% elsif @raffle.entered_users.include?(current_user) && !is_complete?(@raffle) %>
          <input class="btn btn-success" type="submit" value="Entered" disabled>
        <% elsif is_complete?(@raffle) %>
          <input class="btn btn-success" type="submit" value="Ended" disabled>
        <% end %>
        <%= link_to "edit", edit_raffle_path if current_user == @raffle.user %>
      <% else %>
        <h2>The Winner is <%= link_to @raffle.winner.username, user_path(@raffle.winner) %></h2>
      <% end %>  
    </div>
  </div>
</div>