config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "application#home"
  
  get 'browse', to: 'raffles#browse'
  post 'browse', to: 'raffles#browse'
  patch 'funds', to: 'users/users#funds'
  
  
  resources :raffles, only: [:create, :new, :edit, :update, :show, :destroy] do 
    resources :entries, only: [:index, :new]
    post '/entries/new', to: 'entries#create'
    get 'entered_users', to: 'entries#users'
    post 'winner', to: 'entries#winner'  
  end

  


  resources :users, path: 'accounts', param: :username, controller: 'users/users', only: [:show] do
    resources :raffles, only: [:show, :index, :new]
  end
  
  
  devise_for :users, path: 'account', path_names: { sign_in: "login", sign_out: 'logout'},
              controllers: {sessions: 'users/sessions',
                 registrations: 'users/registrations',
                 omniauth_callbacks: 'users/omniauth_callbacks'
                }
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  paginates_per 4
  validates :comment, length: { maximum: 20 }

  belongs_to :user
  belongs_to :raffle

  belongs_to :entered_user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :entered_raffle, class_name: 'Raffle', foreign_key: 'raffle_id'
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_raffle, :authenticate_user!
  skip_before_action :set_raffle, only: [:index]

  def users
    @entries =  @raffle.entries.order(:created_at).reverse_order.page(params[:page])
  end

  def index 
    @raffles = current_user.entered_raffles.order(:created_at).reverse_order.page(params[:page])
  end

  def new
    @entry = Entry.new
  end

  def create 
    if @raffle && can_afford?(@raffle)

      @entry = comment_params[:comment].nil? && comment_params[:comment] == '' ? @raffle.entries.build(user_id: current_user.id) : @raffle.entries.build(user_id: current_user.id,comment: comment_params[:comment])
      if @entry.valid?
        current_user.funds -= @raffle.cost
        @raffle.amount += @raffle.cost
        current_user.save
        @raffle.save
        @entry.save
        redirect_to raffle_path(@raffle), notice: "you succsefully entered the raffle"
      else
        render :new
      end 
    else
      redirect_to raffle_path(@raffle), alert: "Not enough funds"
    end 
  end

  def winner 
    @raffle.winner = @raffle.entered_users.sample
    @raffle.user.funds += @raffle.amount
    @raffle.user.save
    @raffle.save
    redirect_to raffle_entered_users_path
  end

  private

  def set_raffle
    @raffle = Raffle.find(params[:raffle_id])
  end

  def can_afford?(raffle)
    current_user.funds >= raffle.cost 
  end

  def comment_params 
    params.require(:entry).permit(:comment)
  end
end 

app/views/entries/index.html.erb
<% if !@raffles.empty? %>
  <%= render partial: 'raffles/raffles', locals: {raffles: @raffles} %>
  <%= paginate @raffles %>
<% else %>
  <div style="text-align: center;">
    <h2>You are not entered in any raffles </h2>
    <br>
    <h2>Enter a raffle <%= link_to "here.", browse_path %></h2>
  </div>
<% end %>

app/views/entries/new.html.erb
<%= form_for @entry, url: raffle_entries_new_path  do |e| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@entry.errors.count, "error") %> prohibited this post from being saved:</h3>
      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= e.label :comment, 'Enter a comment (optional)' %>
    <%= e.text_area :comment , class:"form-control" %>
    <%= e.submit "Enter", class:"btn btn-success", style: "text-align; center:"%>
  </div>
<% end %>

app/views/entries/users.html.erb
<% if !@entries.empty? %>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-lg-6">
        <div class="list-group">
          <% @entries.each do |entry| %>
            <%= link_to user_path(entry.user), class: "list-group-item list-group-item-action flex-column align-items-start" do %>
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><%= entry.user.username %></h5>
              </div>
              <p><strong>Name: </strong><%= entry.user.name %></p>
              <p><strong>Email: </strong><%= entry.user.email %></p>
              
              <% if !entry.comment.nil? && entry.comment != '' %>
                <p><strong>Comment: </strong><%= entry.comment %></p>
              <% end %>
            <% end %>
          <% end %>
        </div>
        
        <% if @raffle.winner.nil? && is_complete?(@raffle) %>
          <%= button_to "Select winner", raffle_winner_path, style: "text-align: center;", class: "btn btn-success form-btn", method: :post %>
        <% elsif is_complete?(@raffle) %>
          <h5 style="text-align: center;">The Winner is <%= link_to @raffle.winner.username, user_path(@raffle.winner) %></h5> 
        <% end %>
      </div>
    </div>
  </div>
  <%= paginate @entries %>
<% else %>
  <h1 style="text-align: center;">No Users have entered your raffle yet</h1>
<% end %>