config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root "application#home"
  
  get 'browse', to: 'raffles#browse'
  post 'browse', to: 'raffles#browse'
  patch 'funds', to: 'users/users#funds'
  
  
  resources :raffles, only: [:create, :new, :edit, :update, :show, :destroy] do 
    resources :entries, only: [:index, :new]
    post '/entries/new', to: 'entries#create'
    get 'entered_users', to: 'entries#users'
    post 'winner', to: 'entries#winner'  
  end

  


  resources :users, path: 'accounts', param: :username, controller: 'users/users', only: [:show] do
    resources :raffles, only: [:show, :index, :new]
  end
  
  
  devise_for :users, path: 'account', path_names: { sign_in: "login", sign_out: 'logout'},
              controllers: {sessions: 'users/sessions',
                 registrations: 'users/registrations',
                 omniauth_callbacks: 'users/omniauth_callbacks'
                }
  
end

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" >
    <%= link_to "Raffle Dazzle", root_path %>
    <div class="collapse  navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Browse", browse_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My raffles", user_raffles_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Raffle", new_raffle_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View Account", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Entered raffles", raffle_entries_path(current_user), class: "dropdown-item" %>  
            <div class="dropdown-divider"></div>
            <%= link_to "logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
          </div>
        </li>
        <li class="nav-item">
          <%= render "raffles/modal" %>
        </li>
      </ul>
      <%= render 'layouts/search_bar' %>
    </div>
  </nav>
<% else %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" >
    <%= link_to "Raffle Dazzle", root_path %>
    <div class="collapse  navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Browse", browse_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
    <%= render 'layouts/search_bar' %>
  </nav>
<% end %>

app/views/layouts/_search_bar.html.erb
<%= form_tag browse_path, class: "form-inline my-2 my-lg-0"  do %>
  <%= text_field_tag :"raffle[title]", "",class: "form-control mr-sm-2", placeholder: "Search", 'aria-label': "Search", 'type': "Search" %>
  <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RaffleDazzle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
  
</html>